services:
    iido_basic.listener.system:
        class: IIDO\BasicBundle\EventListener\SystemListener
        arguments:
            - "@contao.framework"

    iido_basic.listener.content:
        class: IIDO\BasicBundle\EventListener\ContentListener
        arguments:
            - "@contao.framework"

    iido_basic.listener.page:
        class: IIDO\BasicBundle\EventListener\PageListener
        arguments:
            - "@contao.framework"

    iido_basic.listener.insert_tags:
        class: IIDO\BasicBundle\EventListener\InsertTagsListener
        arguments:
            - "@contao.framework"

    iido_basic.listener.frontend_template:
        class: IIDO\BasicBundle\EventListener\FrontendTemplateListener
        arguments:
            - "@contao.framework"

    iido_basic.listener.combiner:
        class: IIDO\BasicBundle\EventListener\CombinerListener
        arguments:
            - "@contao.framework"

    iido_basic.listener.ajax:
        class: IIDO\BasicBundle\Ajax\ManageAjax

    iido_basic.table.all:
        class: IIDO\BasicBundle\Table\AllTables


#    kernel_bundle:
#      class: IIDO\WebsiteBundle\IIDOWebsiteBundle

#    iido_website.listener.frontend_template:
#        class: IIDO\WebsiteBundle\EventListener\FrontendTemplateListener
#        arguments:
#            - "@contao.framework"

#    iido_website.twig_extension:
#        class: IIDO\WebsiteBundle\Twig\AppExtension
#        public: false
#        tags:
#            - { name: twig.extension }