services:
    contao.iido.connect_tool:
        class: IIDO\BasicBundle\ConnectTool
        arguments:
            - "@database_connection"
            - "%kernel.root_dir%"


    contao.iido.connect_tool_user:
        class: IIDO\BasicBundle\ConnectToolUser
        arguments:
            - "@session"

#    contao.connect_tool_twig_extension:
#        class: SensioLabs\AnsiConverter\Bridge\Twig\AnsiExtension
#        public: false
#        tags:
#            - { name: twig.extension }