services:
    iido_basic.listener.insert_tags:
        class: IIDO\BasicBundle\Listener\InsertTagsListener
        tags:
            - { name: contao.hook, hook: replaceInsertTags, method: replaceCustomizeInsertTags}
        arguments:
        - "@contao.framework"
        public: true

    iido_basic.listener.system:
        class: IIDO\BasicBundle\EventListener\SystemListener
        arguments:
            - "@contao.framework"
        public: true

    iido_basic.listener.content:
        class: IIDO\BasicBundle\EventListener\ContentListener
        arguments:
            - "@contao.framework"
        public: true

    iido_basic.listener.page:
        class: IIDO\BasicBundle\EventListener\PageListener
        arguments:
            - "@contao.framework"
        public: true

    iido_basic.listener.frontend_template:
        class: IIDO\BasicBundle\EventListener\FrontendTemplateListener
        arguments:
            - "@contao.framework"
        public: true

    iido_basic.listener.backend_template:
        class: IIDO\BasicBundle\EventListener\BackendTemplateListener
        arguments:
            - "@contao.framework"
        public: true

    iido_basic.listener.combiner:
        class: IIDO\BasicBundle\EventListener\CombinerListener
        arguments:
            - "@contao.framework"
        public: true

    iido_basic.listener.ajax:
        class: IIDO\BasicBundle\EventListener\AjaxListener
        arguments:
            - "@contao.framework"
            - "@monolog.logger.contao"
        public: true

    iido_basic.listener.form:
        class: IIDO\BasicBundle\EventListener\FormListener
        arguments:
            - "@contao.framework"
        public: true

    iido_basic.listener.news:
        class: IIDO\BasicBundle\EventListener\NewsListener
        arguments:
            - "@contao.framework"
        public: true

    iido_basic.listener.user:
        class: IIDO\BasicBundle\EventListener\UserListener
        arguments:
            - "@contao.framework"
        public: true

    iido_basic.listener.dca:
        class: IIDO\BasicBundle\EventListener\DcaListener
        arguments:
            - "@contao.framework"
        public: true



    iido_basic.table.all:
        class: IIDO\BasicBundle\Table\AllTables
        public: true

    iido_basic.table.global_category:
        class: IIDO\BasicBundle\Table\GlobalCategoryTable
        arguments:
            - "@contao.framework"
            - "@database_connection"
            - "@iido.basic.permission_checker"
        public: true


    iido_basic.twig_extension:
        class: IIDO\BasicBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }


#    iido_basic.module.navigation_controller:
#        class: IIDO\BasicBundle\Module\NavigationController
#        tags:
#            - { name: contao.frontend_module, category: navigationMenu }


#    kernel_bundle:
#      class: IIDO\WebsiteBundle\IIDOWebsiteBundle