contao_iido:
    resource: "@IIDOBasicBundle/Controller"
    type: annotation

#contao_backend_iido_website_config:
#    path: /contao/iido/website/config
#    defaults:
#        _scope: backend
#        _token_check: true
#        _controller: "ContaoBasicBundle:Default:index"

iido_client:
    resource: "@IIDOBasicBundle/Controller"
    type: annotation