services:
#    _instancof:
#        Contao\CoreBundle\Framework\FrameworkAwareInterface:
#            calls:
#                - ["setFramework", ["@contao.framework"]]

#        Symfony\Component\DependencyInjection\ContainerAwareInterface:
#            calls:
#                - ["setContainer", ["@service_container"]]

    contao.connect_tool:
        class: IIDO\BasicBundle\ConnectTool
        arguments:
            - "@database_connection"
            - "%kernel.root_dir%"
            - "%kernel.logs_dir%"


    contao.connect_tool_user:
        class: IIDO\BasicBundle\ConnectToolUser
        arguments:
            - "@session"

#    contao.connect_tool_twig_extension:
#        class: SensioLabs\AnsiConverter\Bridge\Twig\AnsiExtension
#        public: false
#        tags:
#            - { name: twig.extension }

#    iido_basic.module.inheritArticleController:
#        class: IIDO\BasicBundle\Controller\Module\InheritArticleController
##        type: iido_inheritArticle
#        tags:
#            - { name: contao.frontend_module, category: inherit }